[workspace]
members = [
    "crates/crossbeam_playground",
    "crates/learn-rs/config_reader",
    "crates/learn-rs/local_storage_vec"
]

[package]
name = "rs-playground"
version = "0.1.0"
edition = "2024"
