[workspace]
members = ["crates/crossbeam_deque_playground",
    "crates/crossbeam_playground",
    "crates/learn-rs/config_reader",
    "crates/learn-rs/local_storage_vec", 
    "crates/rayon"
]

[package]
name = "rs-playground"
version = "0.1.0"
edition = "2024"
