[package]
name = "config_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.0", features = ["derive"]}
serde_json = "1.0.0"
serde_yaml = "0.9.33"

[[bin]]
name = "learn_rs_config_reader"
path = "src/main.rs"
